site:
  title: pct-compose
  url: https://scarisey.github.io/pct-compose
  start_page: pct-compose::index.adoc
content:
  sources: 
  - url: https://github.com/scarisey/pct-compose
    start_paths: doc
ui: 
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options: "{ startOnLoad: true }"
