name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: openjdk@1.17
    - name: Package
      run: sbt test
