name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: openjdk@1.17
    - name: Package
      run: sbt test
