# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5" # Every week on Friday.
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
