name: Release
on:
  push:
    tags:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v11
      with:
        java-version: openjdk@1.17
    - name: Package
      run: sbt 'test;assembly'
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete ${{ github.ref_name }} --yes || true
        gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes target/scala-3.3.1/pct-compose
