name: Release
on:
  push:
    tags:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: openjdk@1.17
    - name: Create executable
      run: |
        sbt --client 'nativeImageRunAgent " status -d ./src/test/resources/containers.json"' || true
        sbt --client 'nativeImageRunAgent " parse -d ./src/test/resources/containers.json"'
        sbt --client 'nativeImage'
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete ${{ github.ref_name }} --yes || true
        gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes 'target/native-image/pct-compose'
