name: Release
on:
  push:
    tags:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: graalvm@21.0.2=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
    - name: Create executable
      run: sbt 'test;nativeImage'
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete ${{ github.ref_name }} --yes || true
        gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes 'target/native-image/pct-compose'
